# Generated by Django 5.0 on 2024-05-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='course/content')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='testimonial_profiles')),
                ('prevorg', models.TextField(blank=True, null=True)),
                ('prevrole', models.TextField(blank=True, null=True)),
                ('currorg', models.TextField(blank=True, null=True)),
                ('currrole', models.TextField(blank=True, null=True)),
                ('linkdin', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('learn', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='course/thumbnail')),
                ('course_price', models.DecimalField(decimal_places=2, default=2, max_digits=10, null=True)),
                ('content_price', models.DecimalField(decimal_places=2, default=2, max_digits=10, null=True)),
                ('course_price_discounted', models.DecimalField(decimal_places=2, default=2, max_digits=10, null=True)),
                ('content_price_discounted', models.DecimalField(decimal_places=2, default=2, max_digits=10, null=True)),
                ('course_duration', models.IntegerField(default=10)),
                ('course_percentage', models.IntegerField(default=10)),
                ('instructors', models.ManyToManyField(to='user.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False)),
                ('content_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testimonial.course')),
                ('next_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_content_relation', to='testimonial.coursecontents')),
                ('prev_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_content_relation', to='testimonial.coursecontents')),
                ('files', models.ManyToManyField(to='testimonial.filefield')),
            ],
        ),
    ]
