# Generated by Django 5.0 on 2024-05-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontents',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecontents',
            name='files',
        ),
        migrations.RemoveField(
            model_name='coursecontents',
            name='next_content',
        ),
        migrations.RemoveField(
            model_name='coursecontents',
            name='prev_content',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='FileField',
        ),
        migrations.DeleteModel(
            name='CourseContents',
        ),
    ]
