# Generated by Django 5.0 on 2024-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_coursecontents_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
