# Generated by Django 5.0 on 2024-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0004_alter_testimonial_linkdin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='testimonial_profiles'),
        ),
    ]
