# Generated by Django 5.0 on 2024-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0006_alter_testimonial_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='currorg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='currrole',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='prevorg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='prevrole',
            field=models.TextField(null=True),
        ),
    ]
