# Generated by Django 5.0 on 2024-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0007_alter_testimonial_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_testimonial_link',
            field=models.URLField(null=True),
        ),
    ]
