# Generated by Django 5.0 on 2024-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0008_testimonial_video_testimonial_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='video_testimonial_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
