# Generated by Django 5.0 on 2024-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontents',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='course.filefield'),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='video_link',
            field=models.ManyToManyField(blank=True, null=True, to='course.videolinks'),
        ),
    ]
