# Generated by Django 5.0 on 2024-06-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursecontents_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontents',
            name='files',
        ),
        migrations.RemoveField(
            model_name='coursecontents',
            name='video_link',
        ),
        migrations.AddField(
            model_name='coursecontents',
            name='files',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.filefield'),
        ),
        migrations.AddField(
            model_name='coursecontents',
            name='video_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.videolinks'),
        ),
    ]
