# Generated by Django 5.0 on 2024-06-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_coursecontents_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontents',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.filefield'),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='video_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.videolinks'),
        ),
    ]
