# Generated by Django 5.0 on 2024-07-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_googledrivelinks_coursecontents_google_drive_link_and_more'),
        ('course', '0008_remove_coursecontents_files_and_more'),
    ]

    operations = [
    ]
