# Generated by Django 5.0 on 2024-07-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_merge_20240706_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registercourse',
            options={'verbose_name': 'AddStudent', 'verbose_name_plural': 'AddStudents'},
        ),
    ]
