# Generated by Django 5.0 on 2024-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_registercourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivelinks',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='course/thumbnail/filesthumbnail'),
        ),
        migrations.AddField(
            model_name='videolinks',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='course/thumbnail/videothumbnail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='course/thumbnail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='googledrivelinks',
            name='topic_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videolinks',
            name='topic_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
