# Generated by Django 5.0 on 2024-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_googledrivelinks_photo_videolinks_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefield',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
