# Generated by Django 5.0 on 2024-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursecontents_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
