# Generated by Django 5.0 on 2024-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='company_logo',
            field=models.FileField(null=True, upload_to='FeedBackPhoto/CompanyLogo'),
        ),
        migrations.AddField(
            model_name='workshopgallery',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
