# Generated by Django 5.0 on 2024-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_coursefeedback_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopgallery',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
