# Generated by Django 5.0 on 2024-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.ImageField(default='default_profile.jpg', upload_to='profiles/mentor'),
        ),
    ]
