# Generated by Django 5.0 on 2024-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_students_birthday_students_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
