# Generated by Django 5.0 on 2024-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_students_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.FileField(default='default_profile.jpg', upload_to='profiles/instractor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.FileField(default='default_profile.jpg', upload_to='profiles/mentor'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, default='default_profile.jpg', null=True, upload_to='profiles/students'),
        ),
    ]
