# Generated by Django 5.0 on 2024-06-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_instructor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
