# Generated by Django 5.0 on 2024-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_instructor_linkedin_alter_mentor_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='Designation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
