# Generated by Django 5.0 on 2024-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_instructor_designation_alter_instructor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
